#!/bin/bash
# SkipSim Cleanup Script
# Removes unused, deprecated, and commented-out files
# Generated by analysis on 2025-11-10

set -e  # Exit on error

echo "=========================================="
echo "SkipSim Unused Files Cleanup"
echo "=========================================="
echo ""

# Track statistics
TOTAL_REMOVED=0
TOTAL_SIZE=0

# Function to safely remove file
remove_file() {
    local file="$1"
    local reason="$2"

    if [ -f "$file" ]; then
        local size=$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file" 2>/dev/null || echo 0)
        echo "✓ Removing: $file"
        echo "  Reason: $reason"
        rm "$file"
        TOTAL_REMOVED=$((TOTAL_REMOVED + 1))
        TOTAL_SIZE=$((TOTAL_SIZE + size))
    else
        echo "⚠ Already removed or not found: $file"
    fi
    echo ""
}

# Function to safely remove directory
remove_dir() {
    local dir="$1"
    local reason="$2"

    if [ -d "$dir" ]; then
        echo "✓ Removing directory: $dir"
        echo "  Reason: $reason"
        rm -rf "$dir"
        TOTAL_REMOVED=$((TOTAL_REMOVED + 1))
    else
        echo "⚠ Directory not found: $dir"
    fi
    echo ""
}

echo "CATEGORY 1: Old/Deprecated Files with Explicit Markers"
echo "------------------------------------------------------"
remove_file "src/main/java/Blockchain/LightChain/BlockGraphOperations[old].java" \
    "Entire file commented out, marked [old], superseded implementation"

remove_file "src/main/java/ChurnStabilization/BlockLookupEvaluation[deprecated].java" \
    "Entire file commented out, marked [deprecated]"

remove_file "src/main/java/Blockchain/LightChain/blocks.java" \
    "Entire file commented out, replaced by newer implementation"

echo "CATEGORY 2: Commented Out Development/Experimental Code"
echo "-------------------------------------------------------"
remove_dir "src/main/java/Developments" \
    "Entire directory of experimental code, all files commented out"

remove_file "src/main/java/FaultTolerance/RecoveryEvaluation.java" \
    "Entire file commented out, recovery evaluation code not used"

echo "CATEGORY 3: Commented Out Replication Algorithms"
echo "------------------------------------------------"
remove_file "src/main/java/Replication/repTools.java" \
    "1,233 lines of commented LP-based replication tools"

remove_file "src/main/java/Replication/Rep_Alg01_LP.java" \
    "Commented out LP-based replication algorithm"

remove_file "src/main/java/Replication/Rep_Alg05_SubRegion.java" \
    "Commented out SubRegion replication algorithm"

remove_file "src/main/java/Replication/Rep_Alg06_PrivateLP.java" \
    "Commented out Private LP replication algorithm"

remove_file "src/main/java/Replication/Rep_Alg07_PrivateSubRegion.java" \
    "Commented out Private SubRegion algorithm"

remove_file "src/main/java/Replication/Rep_Alg11_SubProblemSubRegion.java" \
    "Commented out SubProblem SubRegion algorithm"

remove_file "src/main/java/Replication/Rep_Alg12_PrivateSubProblemSubRegion.java" \
    "Commented out Private SubProblem SubRegion algorithm"

remove_file "src/main/java/Replication/Rep_Alg13_AdaptiveSubProblemSubRegion.java" \
    "Commented out Adaptive SubProblem algorithm"

remove_file "src/main/java/Replication/Rep_Alg14_PrivateAdaptiveSubProblemSubRegion.java" \
    "Commented out Private Adaptive algorithm"

remove_file "src/main/java/Replication/Rep_Alg15_PrivateRepOnRequesters.java" \
    "Commented out Private replication on requesters"

echo "CATEGORY 4: Commented Out Availability-Based Replication"
echo "--------------------------------------------------------"
remove_file "src/main/java/AvailabilityBasedReplication/AvailabilityRep_Public_Alg03_LPOnAvailability.java" \
    "Commented out availability-based replication algorithm"

remove_file "src/main/java/AvailabilityBasedReplication/AvailabilityRep_Public_Alg04_LPPartOfLARASOnAvailability.java" \
    "Commented out LARAS availability-based algorithm"

remove_file "src/main/java/AvailabilityBasedReplication/AvailabilityRep_Public_Alg05_LPOnMinimizingNumberOfRepsGivenAvailability.java" \
    "Commented out replication minimization algorithm"

remove_file "src/main/java/AvailabilityBasedReplication/AvailabilityRep_Public_Alg06_LPOnMaximizingAvailabilityPerHour.java" \
    "Commented out availability maximization algorithm"

echo "CATEGORY 5: Build Artifacts (Optional)"
echo "---------------------------------------"
if [ -d "out" ]; then
    read -p "Remove build artifacts in out/ directory? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        remove_dir "out" \
            "Compiled .class files (will be regenerated on next build)"
    else
        echo "Skipping out/ directory"
        echo ""
    fi
else
    echo "out/ directory not found or already clean"
    echo ""
fi

echo "CATEGORY 6: Database Files (Optional)"
echo "--------------------------------------"
if [ -f "skipsim3db.db" ]; then
    read -p "Remove simulation database skipsim3db.db? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        remove_file "skipsim3db.db" \
            "Simulation database (will be recreated on next simulation run)"
    else
        echo "Skipping skipsim3db.db"
        echo ""
    fi
else
    echo "skipsim3db.db not found or already removed"
    echo ""
fi

echo "=========================================="
echo "Cleanup Summary"
echo "=========================================="
echo "Files/directories removed: $TOTAL_REMOVED"
if [ $TOTAL_SIZE -gt 0 ]; then
    echo "Total size freed: $(numfmt --to=iec-i --suffix=B $TOTAL_SIZE 2>/dev/null || echo $TOTAL_SIZE bytes)"
fi
echo ""
echo "✅ Cleanup complete!"
echo ""
echo "Next steps:"
echo "1. Verify the build still works: make clean && make compile && make test"
echo "2. Commit the changes: git add -A && git commit -m 'Remove unused and deprecated files'"
echo ""
